### ISSUE TITLE
[Code to RAML] Unsupported sub annotations of RequestMapping

### ISSUE THREAD

**Issue by bendem** [phoenixnap/springmvc-raml-plugin#103]
Annotations such as `GetMapping`, `PostMapping` and custom annotations annotated with `RequestMapping` are not handled.

An easy fix would be to use `AnnotatedElementUtils.getMergedAnnotation(element, RequestMapping.class)` instead of `element.getAnnotation(RequestMapping.class)` ([as spring actually does internally](https://github.com/spring-projects/spring-framework/blob/ed6c5330797f790439db31cff95863a34533a0b6/spring-web-reactive/src/main/java/org/springframework/web/reactive/result/method/annotation/RequestMappingHandlerMapping.java#L200)).

**Comment by bendem** [comment]
I'd start by changing it [here](https://github.com/phoenixnap/springmvc-raml-plugin/blob/1764c28cd2aac0bba09f94c1ded5c203ee42d683/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/parser/SpringMvcResourceParser.java#L170), then potentially move all `getAnnotation` calls for spring annotations to use it as well.

**Comment by kurtpa** [comment]
good point, added to my todo :)

**Comment by kurtpa** [comment]
Sorry this slipped my radar, fix will be released with 0.9.1

**Comment by bendem** [comment]
thanks
