### ISSUE TITLE
generate asynchronous server and client code

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#104]
Hi,

I was thinking about having my services being asynchronous, Do you have a Rule to generate server code from raml that returns `DeferredResult` ?

Same question for client code generation : is there a rule to be able to use an `AsyncRestTemplate` ?

**Comment by kurtpa** [comment]
That is a very good idea, however we dont have a rule for this yet i'm afraid

**Comment by techpavan** [comment]
I guess the DeferredResult never came in as a PR. And Callable is not really a great performance enhancer.
