### ISSUE TITLE
Responses for status code 202 (Accepted) do not generate classes for JSON schema

### ISSUE THREAD

**Issue by tofcoder** [phoenixnap/springmvc-raml-plugin#105]
Only responses with status codes 200 (OK) or 201 (Created) are able to generate classes for JSON schema.

**Comment by kurtpa** [comment]
merged! will be included in next release :)

**Comment by tofcoder** [comment]
@kurtpa: Would it be possible to have a new release? I would need this bug fix. Thanks.

**Comment by stojsavljevic** [comment]
It has been released with 0.8.8.
