### ISSUE TITLE
no pattern checking for query parameters

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#108]
Hello,

I defined in a raml, a query parameter with a pattern:

```
...
        myQueryParam:
          type: string
          required: true
          repeat: false
          pattern: |
              ^.{1,255}$
...
```

The issue is that the generated decorator does not reflect the `pattern` and the `required`fields .
I would expect the decorator method to have something like :

```
...
        @RequestParam
        @NotNull //expected
        @Pattern(regexp = "^.{1,255}$")  //expected
        String myQueryParam,
...
```

That leads to differences between what is exposed by the raml and the code.

**Comment by kurtpa** [comment]
I don't think we can support this, i've tried experimenting with @Valid and @Pattern alongside the query parameters and path variables within the method signature and spring seems to ignore them. From our end we use jsonschema2pojo to generate objects and that supports JSR303 annotation checking

**Comment by kurtpa** [comment]
if you have any code examples of how this works, i'd love to see it
