### ISSUE TITLE
generate json schema from POJO using jackson with custom serializers

### ISSUE THREAD

**Issue by rakeshjain0512** [phoenixnap/springmvc-raml-plugin#109]
I've a class say, DateBean which contains 3 fields viz. int day, int month & int year.
I have added a custom serializer to represent object of DateBean as a string with format - 'yyyy-MM-dd'

It is working fine during serialization while returning response.
Now, I want to generate schema of a response class which contains DateBean as property with the same custom serializer.

I tried with something like below, but it didn't work.

SimpleModule simpleModule = new SimpleModule();
simpleModule.addSerializer(DateBean.class, new JsonDateBeanSerializer());		mapper.registerModule(simpleModule);
SchemaFactoryWrapper visitor = new SchemaFactoryWrapper();
mapper.acceptJsonFormatVisitor(clazz, visitor);
JsonSchema schema = visitor.finalSchema(); 

It is even not going into serialize method of my custom serializer class, while generating schema.
In my schema, DateBean property get represented as Object with properties day, month & year. 
However I want it should be like "type":"string" with format.

Can you please suggest how could I get JsonSchema of a POJO class with support of Custom Serializer

**Comment by kurtpa** [comment]
We use jackson for this functionality, i'd suggest you check there for this i'm afraid
