### ISSUE TITLE
JSON schema extension not supported

### ISSUE THREAD

**Issue by wbsouza** [phoenixnap/springmvc-raml-plugin#116]
I'm trying to extend [this JSON schema definition](https://spacetelescope.github.io/understanding-json-schema/structuring.html#extending) but the maven plugin generates the Java code as Object instead of the new object type.

**Comment by kurtpa** [comment]
springmvc-raml-plugin currently uses jsonschema2pojo for POJO generation and this does not support extension. Whilst we may add more flexibilty as part of the upgrade to support RAML 1.0, we are unable to support this for now
