### ISSUE TITLE
repeat in queryParam in RAML 0.8 when generating controllers

### ISSUE THREAD

**Issue by tspaeth** [phoenixnap/springmvc-raml-plugin#117]
Hi!

I'm wondering, why a query parameter with
```
repeat: true
```

does not work somehow if generating controllers for Spring etc. - did this ever do or is the implementation not finished? Does somebody have an example how to specify it in a RAML file then if it should be working with 0.8?

**Comment by kurtparis** [comment]
If memory serves,  this should generate an array of whatever the type is specified. I'll check in more detail tomorrow

**Comment by tspaeth** [comment]
Thanks. To be a bit more precise after rereading my post - yup I would also expect the Controller "header" to be 
´´´
String[] foo
´´´
instead of
´´´
String foo
´´´
for these params

**Comment by kurtpa** [comment]
This should be included in the next release
