### ISSUE TITLE
[Question] When to push 0.9 version to maven central?

### ISSUE THREAD

**Issue by baihe** [phoenixnap/springmvc-raml-plugin#123]
Hi guys:
I am not very familiar with the "maven central" process so throw this question here.

I found 0.8 (which is on the maven central) not support GetMapping shorthand annotations, but after I pull the source I found it already supported.
I believe current 0.9 version is still in development, since no tag for 0.9 version yet.
Is there any plan for the release of this version now?

Thanks for your effort on this great plugin.

**Comment by kurtparis** [comment]
Apologies, i will release this later today

**Comment by kurtpa** [comment]
done! :) sorry for the delay
