### ISSUE TITLE
raml plugin cannot find source for class in dependent library

### ISSUE THREAD

**Issue by EvilJinious1** [phoenixnap/springmvc-raml-plugin#124]
I just started to use this plugin for a project.  It works well enough for code contained in the system and  3rd parties.

However, I have a class in one of my dependent libraries that I include and the plugin complains that it cannot find the source.

I generated a master java doc directory of all the dependent libraries that I use and included it in my usage of the plugin to generate the raml specification.

here is how I define the raml plugin

<profile>
            <id>generate-raml</id>
            <build>
                <plugins>
                    
                    <plugin>
                        <groupId>com.phoenixnap.oss</groupId>
                        <artifactId>springmvc-raml-plugin</artifactId>
                        <version>${raml.plugin.version}</version>
                        <configuration>
                            <javaDocPath>/Users/larrymitchell/phiupdate/nfvusvcssupport/apidocs</javaDocPath>
                            <outputRamlFilePath>${raml.spec.path}</outputRamlFilePath>
                            <restBasePath>/</restBasePath>
                            <version>${project.version}</version>
                            <includeGlobalMediaType>false</includeGlobalMediaType>
                            <restrictOnMediaType>false</restrictOnMediaType>
                            <documentationSuffix>${project.name}</documentationSuffix>
                        </configuration>
                        <executions>
                            <execution>
                                <id>generate-springmvc-api-docs</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>generate-springmvc-api-docs</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

The java doc path points to the javadoc directory
I ran maven with the -X option to see what the issue was 

[WARNING] *** WARNING: Missing Source for: ExampleController. JavaDoc Unavailable.
[INFO] Added call: /v1/example/testecho GET from method: testEcho
[DEBUG] Getting Javadoc for: PhiGeneralResponse
[DEBUG] /Users/larrymitchell/phiupdate/nfvusvcssupport/apidocs
... remainder cut for brevity ...
[DEBUG] /Users/larrymitchell/phiupdate/nfvusvcssupport/apidocs/com/cisco/phisphere/foundations/common

Note that foundations common is where the class is described via javadoc
note that if we ls this directory
LARMITCH-M-L2BE:ramlservice larrymitchell$ ls -l /Users/larrymitchell/phiupdate/nfvusvcssupport/apidocs/com/cisco/phisphere/foundations/common
total 152
-rw-r--r--   1 larrymitchell  staff  41901  1 Mar 09:53 PhiGeneralResponse.html
drwxr-xr-x   3 larrymitchell  staff    102  1 Mar 09:51 class-use
drwxr-xr-x  13 larrymitchell  staff    442  1 Mar 09:51 exceptions
drwxr-xr-x   8 larrymitchell  staff    272  1 Mar 09:51 json
drwxr-xr-x  10 larrymitchell  staff    340  1 Mar 09:51 metrics
-rw-r--r--   1 larrymitchell  staff   1045  1 Mar 09:53 package-frame.html
-rw-r--r--   1 larrymitchell  staff   5555  1 Mar 09:53 package-summary.html
-rw-r--r--   1 larrymitchell  staff   5590  1 Mar 09:53 package-tree.html
-rw-r--r--   1 larrymitchell  staff  10673  1 Mar 09:53 package-use.html
drwxr-xr-x   9 larrymitchell  staff    306  1 Mar 09:51 stream

I see that it scans through the whole javadoc collection and fails to find the  PhiGeneralResponse class that needs referencing.
....  the end of the scan ....
[DEBUG] /Users/larrymitchell/phiupdate/nfvusvcssupport/apidocs/com/cisco/phisphere/swagger/controller/class-use
[WARNING] *** WARNING: Missing Source for: PhiGeneralResponse. JavaDoc Unavailable.
[INFO] Parsing resource: ExampleController 

Is there something else that needs to be done to get this to work?

**Comment by kurtpa** [comment]
One of the slowest parts of the generation process was the searching of files on disk. As such we added a number of heuristics to allow the search algorithm to remove large parts of search space to improve the speed.

If you take a look at https://github.com/phoenixnap/springmvc-raml-plugin/commit/40649fb1a8f7126cee5258f940b73b39bfce7674 you will see that the plugin expects source code to follow the Maven/Gradle folder structure (src/main/java) and will skip other folders.

You can either try change the folder you are using to accomodate this heuristic, alternatively we will welcome a PR that allows these to be switched on/off via configuration

**Comment by EvilJinious1** [comment]
Thanks for getting back to me.
I was assuming that it would search the generated javadoc code for the specific external element, which in my case is PhiGeneralResponse.html in that folder.
Ok, I suppose I can restructure the generated javadoc to accommodate that structure.
My projects do follow the maven structure.  src/main/java

**Comment by kurtpa** [comment]
no problem, keep in mind that it parses the actual source code (.java) files, not the generated html javadoc files

**Comment by EvilJinious1** [comment]
ok, so then I misunderstood.  
The missing class PhiGeneralResponse.java is in another project.  So from your comments, I would be pointing at that other source directory.  Which configuration directive is used for that?

**Comment by kurtpa** [comment]
currently we support 1 folder which you can configure using this maven config: <javaDocPath>D:/</javaDocPath>

Since only one path is supported you would need to give it a folder that is the root of all your projects i'm afraid. If this doesnt work for you it can be extended quite easily to support an array of folders (however we currently do not have the resources for this since we are focusing on RAML 1.0 support)

**Comment by EvilJinious1** [comment]
I tried putting my projects under one folder and it worked by generating the raml.
It was my misunderstanding of what <javaDocPath> was for.
I will take a look at the multiple folder issue.  I have a few things ahead of it so it might a take a week before I can get to it.
