### ISSUE TITLE
[RAML to Code] Support configurable generic ResponseEntity

### ISSUE THREAD

**Issue by AdminAffe** [phoenixnap/springmvc-raml-plugin#125]
For example, I have the following RAML specification:
```
[...]
responses:
      200:
        body:
          application/json:
            schema: VerifyResponse
            example: |
              {
                "name": "developer",
                "authtoken": "<TOKEN>"
              }
      401:
        body:
          application/json:
            schema: ErrorResponse
            example: |
              {
                "status": "401",
                "statusText": "BAD_REQUEST",
                "validationErrorsJSON": {
                    "mtan": [
                      "Invalid mTAN"
                    ]
                  },
                "path": "/api/mtan/verify"
              }
```
My problem now is that the generated method only returns ResponseEntity&lt;VerifyResponse&gt;.
What I need though, is the possibility to return both VerifyResponse and ErrorResponse.
I don't know if there is already a way to accomplish this via the existing configuration, but in case there isn't I would recommend a new configuration property to explicitly enable the generation of a generic ResponseEntity. I assume changing the following line within the [RamlParser](https://github.com/phoenixnap/springmvc-raml-plugin/blob/master/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/generation/RamlParser.java) should do the trick:
```
if (!generateGenericResponse && childResource.getValue().getResponses() != null) {
	response = RamlHelper.getSuccessfulResponse(childResource.getValue());
}
```

**Comment by kurtpa** [comment]
Our assumption thus far is that only successful responses are returned by the method, since errors are typically thrown as exceptions and then caught/transformed by spring's @ExceptionHandlers. I agree that this would be easy to achieve, however i'm not 100% sure of the logical implications it would raise.

Using RAML 1.0 types we could achieve this using a common parent type whilst keeping the same structure

Anyone have any opinions on this?

**Comment by AdminAffe** [comment]
I never thought of using the ExceptionHandler annotation before. Thanks for the hint. 😄 
If you take this into consideration, the behavior of the RamlParser actually makes pretty good sense.
I changed the behavior of my controller accordingly, so basically this issue became obsolete. 
But maybe there is someone else who could think of a useful use case for such behavior.

**Comment by kurtpa** [comment]
I'm going to close this issue for now, if anyone needs this usecase feel free to reopen this and we can discuss
