### ISSUE TITLE
format definition does not work if it is used in endpoint definition

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#136]
If `format: int32` is set for the resource type generated property type is `Integer`.
But, if same format is used for the enpoint definition property type is `Long`.

Example:
```
  /api:
    /products:
      /items:
        get:
          queryParameters:
            itemId:
              type: integer
              format: int32

          responses:
            200:
              body:
                application/json:
                  schema:
                    ItemResource
```

**Comment by kurtpa** [comment]
I think this was done since format was not available in 0.8 and we were defensively always picking Long, since accepting a Long allows for both Integer and Long parameters. 

If we want to start discriminating, we can add this on a best effort basis :)

**Comment by kurtpa** [comment]
From some preliminary investigation, it seems that we need to combine the new Interpreters with the code in the SchemaHelper.java:mapSimpleType

**Comment by piffta** [comment]
Tested, it works now.
Thanks a lot.
