### ISSUE TITLE
Verify RAML implementation in 1.0

### ISSUE THREAD

**Issue by shucoshuco** [phoenixnap/springmvc-raml-plugin#138]
Hi,

I started using this library to validate my Spring MVC implementation against a RAML definition. It works pretty well, thanks a lot.

I have found a couple of issues I would like to ask if they are some bugs or it is worked as intended for some reason.

RamlVerifier class hardcodes the creation of the factory to use always version 0.8. I changed it to detect the version depending on RAML file header and it worked.

Some methods in class RJP10V2RamlQueryParametere raise an UnsupportedOperationException in case the type of the parameter is different from expected one. But the class that uses this methods expects they return a null value if the validation does not apply. Therefor, I got this exception for any parameter. I tried returning null values instead of throwing the exception and everything works as expected.

This is a very useful libraty. Good job.

Regards,

Félix.

**Comment by kurtpa** [comment]
The hardcoding of 0.8 was intentional since at present we can only go from RAML -> code with 1.0 support.  With the file you tested, did you also include any Raml Types (1.0)?

Changing the QueryParameter to return null instead of throwing an exception makes sense

**Comment by shucoshuco** [comment]
Yes, I have some types definition, and it is working.

**Comment by kurtpa** [comment]
Cool! :) good to know :) 

i'll apply these changes to 0.10.3
