### ISSUE TITLE
Incorrect POJO name for resources of type array

### ISSUE THREAD

**Issue by lclement57** [phoenixnap/springmvc-raml-plugin#139]
When defining a resource named `addresses`, the generated file is `Addres.java` instead of `Address.java`

The raml file contains:
```
schemas:
  - Address: !include schemas/address.json
  - Addresses: !include schemas/addresses.json

/addresses:
  displayName: Addresses
  get:
    responses:
      200:
        body:
          application/json:
            schema: Addresses
```

And the schemas:
```
{
   "$schema": "http://json-schema.org/draft-04/schema",
   "id": "Addresses",
   "type": "array",
   "uniqueItems": true,
   "items": {
      "$ref": "pojogen/address.schema"
   }
}
```

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "Address",
    "type": "object",
    "properties": {
        "tString": {
            "type": "string",
            "description": "The type string."
        }
    }
}
```

To reproduce the issue, you may add a unit test in `JsonSchema2PojoTest` that parses the 2 schema files:
```
    @Test
    public void schemaHelper_ExtractsArray_Plural() throws Exception {
        URL url = Resources.getResource(path + "addresses.schema");
        String text = Resources.toString(url, Charsets.UTF_8);
        ApiBodyMetadata mapSchemaToPojo = SchemaHelper.mapSchemaToPojo(null, text, "com.test", "Fallback", null);
        assertThat(mapSchemaToPojo.isArray(), is(true));
        assertThat(mapSchemaToPojo.getName(), is("Address"));
    }
```

The problem seems to be that in the `mapSchemaToPojo` method, when we resolve the schema name, if it is an array we look for the subschema referenced in `$ref` and use it's ID as a name, thus for the **Addresses** resource we obtain **Address**. [SchemaHelper.java#L560](https://github.com/phoenixnap/springmvc-raml-plugin/blob/master/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/naming/SchemaHelper.java#L560)

Then, we instantiate `ApiBodyMetadata` with the resolved name **Address** and we singularize the name passed as parameter, since it is already a singular, it fails and gives **Address** -> **Addres**. [ApiBodyMetadata.java#L94](https://github.com/phoenixnap/springmvc-raml-plugin/blob/master/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/data/ApiBodyMetadata.java#L94)

I'm not sure of the impacts, maybe in [ApiBodyMetadata.java#L94](https://github.com/phoenixnap/springmvc-raml-plugin/blob/master/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/data/ApiBodyMetadata.java#L94) we should disable singularization for `array` types ?

**Comment by kurtpa** [comment]
I think the issue lies in the InflectorBase which is not handling words ending in double s correctly for singularisation. I have added a small fix and will be providing a pull request for the raml parser
