### ISSUE TITLE
QueryParam/RequestParams are not getting added in method body of controller with generate endpoints plugin

### ISSUE THREAD

**Issue by rakeshjain0512** [phoenixnap/springmvc-raml-plugin#15]
Hi,
I'm trying to generate controller and model classes using a RAML file. I observed that 'generate-endpoints' plugin is not generating the code as I'm expecting for RAML having queryParameters.
The method in the controller does not have a @QueryParam or @RequestParam in it.

Herewith, I've attached a sample RAML with HTTP get method resource and queryParameters used in it.

Below is the sample method which get generated using plugin.
`/**
	 * No description
	 */
	@RequestMapping(value="", method=RequestMethod.GET)
	public @ResponseBody LocateCustomerByCardResponseSchema getCustomersCard (@RequestParam("id") String id) { 
	
		 //TODO Autogenerated Method Stub. Implement me please.
		 return null;
	}`

Kindly take a look and assist for this issue.
[api.txt](https://github.com/phoenixnap/springmvc-raml-plugin/files/140502/api.txt)

**Comment by kurtpa** [comment]
There is @RequestParam in front of the id parameter in the method. I'm not understanding what is wrong here :(

**Comment by rakeshjain0512** [comment]
Apologies. I pasted the wrong code.

here is the actual method that get generated with the RAML given earlier.

`	@RequestMapping(value="", method=RequestMethod.GET)
	public @ResponseBody LocateCustomerByCardResponseSchema getCustomersCard () { 
	
		 //TODO Autogenerated Method Stub. Implement me please.
		 return null;
	}`

thanks in advance for ur help!

**Comment by kurtpa** [comment]
Ah oki now i understand :)

Are you using version 0.2.1 or 0.2.2?

**Comment by rakeshjain0512** [comment]
its version=0.2.1

**Comment by kurtpa** [comment]
doh found the issue, this is an embarraingly stupid bug sorry :( - committing fix now :)

**Comment by kurtpa** [comment]
Committed to 0.2.3 and released to central. Let me know how it goes :)
