### ISSUE TITLE
NullPointerException validating RAML

### ISSUE THREAD

**Issue by shucoshuco** [phoenixnap/springmvc-raml-plugin#150]
Hi,

I think I found a bug in class com.phoenixnap.oss.ramlapisync.raml.rjp.raml10v2.RJP10V2RamlQueryParameter.

Both methods getMinimum() and getMaximum() wrap the value returned by queryParameter object into a BigDecimal. It fails in case this value is null, raising a NullPointerException, so every parameter without maximum or minimum breaks the validation of RAML files.

Regards,
Félix.

**Comment by stojsavljevic** [comment]
If I'm not mistaken, you're trying to keep RAML 1.0 in sync with Spring code.
Unfortunately, this is not supported atm for 1.0 version of RAML. We're only supporting code generation from RAML 1.0.
But PRs are more than welcome :)
