### ISSUE TITLE
Collision with java keywords

### ISSUE THREAD

**Issue by nikitapavlenko** [phoenixnap/springmvc-raml-plugin#152]
Hello guys,

I faced with an issue that generated interface for controller was not compiled due to collision of generated name with java `default` keyword.

Given RAML:
[api.raml](https://devportal.yaas.io/services/beta/account/v1/api.raml)

Compilation errors:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project drinks-server: Compilation failure: Compilation failure:
[ERROR] /home/mpavlenko/repos-private/springmvc-raml-plugin-sample/drinks-server/target/generated-raml-mvc/com/phoenixnap/oss/sample/server/rest/ProjectControllerDecorator.java:[235,60] <identifier> expected
[ERROR] /home/mpavlenko/repos-private/springmvc-raml-plugin-sample/drinks-server/target/generated-raml-mvc/com/phoenixnap/oss/sample/server/rest/ProjectControllerDecorator.java:[235,68] ';' expected
[ERROR] /home/mpavlenko/repos-private/springmvc-raml-plugin-sample/drinks-server/target/generated-raml-mvc/com/phoenixnap/oss/sample/server/rest/ProjectControllerDecorator.java:[236,84] illegal start of expression
[ERROR] /home/mpavlenko/repos-private/springmvc-raml-plugin-sample/drinks-server/target/generated-raml-mvc/com/phoenixnap/oss/sample/server/rest/ProjectControllerDecorator.java:[236,91] ';' expected
[ERROR] /home/mpavlenko/repos-private/springmvc-raml-plugin-sample/drinks-server/target/generated-raml-mvc/com/phoenixnap/oss/sample/server/rest/ProjectController.java:[120,149] <identifier> expected
[ERROR] /home/mpavlenko/repos-private/springmvc-raml-plugin-sample/drinks-server/target/generated-raml-mvc/com/phoenixnap/oss/sample/server/rest/ProjectController.java:[120,157] ';' expected
`

The specific example of a line that is not compiled:
`
public ResponseEntity<CreateRoleResponse> createRole(String projectId, String authorization, com.phoenixnap.oss.sample.server.rest.model.Default default);
` 

I believe it can be fixed on the stage of source code generation by checking such special cases.

 Kind regards,
Mykyta

**Comment by stojsavljevic** [comment]
Thanks for reaching us.
Can you please try to isolate problematic part in your raml?
Providing minimal sample that reproduces the problem would be very helpful.

**Comment by champagne** [comment]
@nikitapavlenko ，
I have tried your raml with plugin 0.10.7, there're so many errors in your raml file.
- application:/json:
- Duplicated key 'application/json'
- Unrecognized token 'organizationRoleUpdate'
- Unrecognized token 'defaultPaymentMethod'
- Unrecognized token 'members'
- Unrecognized token 'member'

Please fix them first.

Xiangbin HAN

**Comment by alemateo** [comment]
Hi,

First of all thanks for this excellent project.
I having the next problem that is not the same that is happening to @nikitapavlenko but is regarding Java private keywords as model's class name.

I'm working with an API that has the next definition for a type import:

```
types:
  import:
    type: object
    properties:
      amount:
        type: number
        required: false
        description: |
          Monetary amount.
      currency:
        type: string
        required: false
        description: |
          String based on ISO-4217 for specifying the currency related to the amount.
```

The problem is that the Model generated for the type is:

```
public class import implements Serializable {
...
}
```

As you can guess this class doesn't compile. 
My problem is that I can't modify the API definition. Right now the only solution I found is to modify the generated class by hand. And this is something that I want to avoid for several reasons.

So, I was wondering if someon can help me to find a programmatic solution for this.

I have been trying to force the parser to write the class name capitalised but so far I always ended brokening something.

Thanks

**Comment by stojsavljevic** [comment]
Hi all,

I discovered collision with java keywords in some cases and I'm working on the solution.

But I couldn't reproduce the issue @alemateo reported - I'm getting POJO named `Import` which is fine.
Can you please recheck with some newer version of the plugin?
