### ISSUE TITLE
Generates raml specs even if Code is commented 

### ISSUE THREAD

**Issue by it-sumanp** [phoenixnap/springmvc-raml-plugin#16]
In my code I commented whole Controller File , but still RAML specs are getting generated for that class

**Comment by kurtpa** [comment]
I could not replicate this - commenting methods/controllers in the tests removed them from the RAML model . The Generator works by using reflection so if the code is not compiled it would not have access to the methods.
Double check that compiled classes are not still present from a previous compilation or dependency jar.
If you can't find where it's coming from, you can ignore specific packages and controller with the following configuration
```
<ignoredList>
       <param>com.package.to.ignore</param>
       <param>com.specificClass.to.ignore.ClassName</param>
</ignoredList>
```

**Comment by kurtpa** [comment]
Either way, commenting big chunks of code is an anti pattern and will dirty your SCM :)

**Comment by it-sumanp** [comment]
@kurtpa thanks man .
