### ISSUE TITLE
Does this plugin support Spring Boot project?

### ISSUE THREAD

**Issue by DevinTan** [phoenixnap/springmvc-raml-plugin#160]
I use this plugin in a Spring Boot project, and I got below errors:
[ERROR] Unable to get methods - skipping class class com.***Controller
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findClassMethods(AnnotatedClass.java:1195)
.....

**Comment by stojsavljevic** [comment]
Hi

Thanks for reaching us.
IIRC, this stack trace is coming from Jackson but it shouldn't have high impact.
Can you please provide small example so we can take a look?

And yes, this plugin supports Spring Boot :)

**Comment by DevinTan** [comment]
Sorry, maybe it's due to my wrong usage. The cause of the exception is that there is a method which return ModelAndView instead of RESTFUL API in my controller class, when i removed the method, everything is OK.

**Comment by stojsavljevic** [comment]
Yes, you're right - having `ModelAndView` will cause the stack trace to occur.

However, MVC paradigm does not fit in REST world so I see this issue as a minor one.

What you can do in case you're stuck with `ModelAndView` in certain controller is to exclude it from raml generation with `ignoredList` parameter - https://github.com/phoenixnap/springmvc-raml-plugin/tree/master/springmvc-raml-plugin#ignoredlist
