### ISSUE TITLE
JsonParse Exception when generating the code for RAML 1.0

### ISSUE THREAD

**Issue by jancallewaert** [phoenixnap/springmvc-raml-plugin#168]
When I generate an interface for a RAML 1.0 specification, I get a Json Parse Exception.

This is the specification:
```
#%RAML 1.0
title: spring-boot-example
version: "0.0.1"
baseUri: /
/messages: 
    displayName: Messages Resource
    description: Messages Resource
    post: 
        description: createMessage
        body: 
            application/json: 
                schema: Message
        responses: 
            "202":
                description: Successful Response

    get: 
        description: getMessages
        responses: 
            "200": 
                description: Successful Response
                body: 
                    application/json: 
                        schema: ListMessagesResponse
#            "404":
#                body:
#                    application/json:
#                        schema: HttpProblem
    /{id}:
        displayName: "{id} Resource"
        description: "{id} Resource"
        get: 
            description: getMessage
            responses: 
                "200": 
                    description: Successful Response
                    body: 
                        application/json: 
                            schema: Message
                "404":
                    body:
                        application/json:
                            schema: HttpProblem
types:
    ListMessagesResponse:
        properties:
            messages:
                type: Message[]
                minItems: 0
                required: true

    Message:
        properties:
            value:
                required: true
                type: string

    HttpProblem:
        properties:
            title:
                type: string
                required: true
```

And this is the error:
```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'object': was expecting ('true', 'false' or 'null')
 at [Source: object; line: 1, column: 13]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2381)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:116)
	at com.phoenixnap.oss.ramlapisync.naming.SchemaHelper.buildBodyJCodeModel(SchemaHelper.java:626)
	at com.phoenixnap.oss.ramlapisync.naming.SchemaHelper.mapSchemaToPojo(SchemaHelper.java:561)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.generateUnreferencedSchemas(SpringMvcEndpointGeneratorMojo.java:276)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.generateEndpoints(SpringMvcEndpointGeneratorMojo.java:260)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.execute(SpringMvcEndpointGeneratorMojo.java:464)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by champagne** [comment]
Hi @jancallewaert ,
Please update the springmvc-raml-plugin to the latest 0.10.7.
I have tried your raml file with the latest version 0.10.7, and it works fine.

`
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Spring MVC RAML Synchronizer Sample
[INFO] Drinks Server
[INFO] Drinks Client
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring MVC RAML Synchronizer Sample 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ springmvc-raml-plugin-sample ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ springmvc-raml-plugin-sample ---
[INFO] Installing C:\Sam\works\springmvc-raml-plugin-sample-2\pom.xml to C:\Users\myname\.m2\repository\com\phoenixnap\oss\springmvc-raml-plugin-sample\0.0.1\springmvc-raml-plugin-sample-0.0.1.pom
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Drinks Server 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ drinks-server ---
[INFO] Deleting C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ drinks-server ---
[INFO] Source directory: C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target\generated-raml-mvc added.
[INFO] 
[INFO] --- springmvc-raml-plugin:0.10.7:generate-springmvc-endpoints (generate-springmvc-controllers) @ drinks-server ---
[INFO] RJP10V2RamlModelFactory Instantiated
[INFO] Adding Interpreter ObjectTypeInterpreter for type ObjectTypeDeclaration
[INFO] Adding Interpreter BooleanTypeInterpreter for type BooleanTypeDeclaration
[INFO] Adding Interpreter NullTypeInterpreter for type NullTypeDeclaration
[INFO] Adding Interpreter NumberTypeInterpreter for type NumberTypeDeclaration
[INFO] Adding Interpreter ArrayTypeInterpreter for type ArrayTypeDeclaration
[INFO] Adding Interpreter AnyTypeInterpreter for type AnyTypeDeclaration
[INFO] Adding Interpreter FileTypeInterpreter for type FileTypeDeclaration
[INFO] Adding Interpreter DateTypeInterpreter for type DateTimeOnlyTypeDeclaration
[INFO] Adding Interpreter DateTypeInterpreter for type DateTimeTypeDeclaration
[INFO] Adding Interpreter DateTypeInterpreter for type DateTypeDeclaration
[INFO] Adding Interpreter DateTypeInterpreter for type TimeOnlyTypeDeclaration
[INFO] Adding Interpreter UnionTypeInterpreter for type UnionTypeDeclaration
[INFO] Adding Interpreter StringTypeInterpreter for type StringTypeDeclaration
[INFO] Generating Code for Resource: Message
com\phoenixnap\oss\sample\server\rest\model\ListMessagesResponse.java
com\phoenixnap\oss\sample\server\rest\model\Message.java
com\phoenixnap\oss\sample\server\rest\MessageController.java
[INFO] Endpoint Generation Complete in:889ms
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ drinks-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ drinks-server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 14 source files to C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ drinks-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ drinks-server ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ drinks-server ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ drinks-server ---
[INFO] Building jar: C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target\drinks-server-0.0.1.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:repackage (default) @ drinks-server ---
[INFO] Attaching archive: C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target\drinks-server-0.0.1-exec.jar, with classifier: exec
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ drinks-server ---
[INFO] Installing C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target\drinks-server-0.0.1.jar to C:\Users\myname\.m2\repository\com\phoenixnap\oss\drinks-server\0.0.1\drinks-server-0.0.1.jar
[INFO] Installing C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\pom.xml to C:\Users\myname\.m2\repository\com\phoenixnap\oss\drinks-server\0.0.1\drinks-server-0.0.1.pom
[INFO] Installing C:\Sam\works\springmvc-raml-plugin-sample-2\drinks-server\target\drinks-server-0.0.1-exec.jar to C:\Users\myname\.m2\repository\com\phoenixnap\oss\drinks-server\0.0.1\drinks-server-0.0.1-exec.jar

`

BR,
Xiangbin HAN

**Comment by stojsavljevic** [comment]
Hi,

thanks for checking this @champagne 
Yes, it also works for me with `0.10.7`.

@jancallewaert can you test with `0.10.7` also?
Another thing, what rule do you use?

**Comment by gurajala1987** [comment]
Using 0.10.9 springmvc-raml-plugin, still facing the same issue. Also, could compile the project after downloading this. Have to compile the project using the command 
mvn clean install -DskipTests=true
to disable the test execution. Could some one please help me with this ?

**Comment by stojsavljevic** [comment]
@jancallewaert 

Please post your maven config. Or even better, create sample application that reproduces your issue.

I tried this again using `0.10.8` (latest release) with `Spring4ControllerInterfaceRule` and the build is successful.
Also, I don't understand what is the issue - compile or tests since you're skipping them with `-DskipTests=true`.

**Comment by kurtpa** [comment]
@jancallewaert are you using Maven 2 or 3?

**Comment by gurajala1987** [comment]
@kurtpa using maven 3.3.9.

**Comment by bbd127** [comment]
@gurajala1987 There is an issue in the tests. I patched that up as a part of the pull request for issue GH-178. 

Cheers

**Comment by gurajala1987** [comment]
@stojsavljevic @jancallewaert @bbd127  The parsing error disappeared when I changed the value of _<generateUnreferencedSchemas>false</generateUnreferencedSchemas>_  from true to false. I don't know if I would be loosing some functionality by making it false.

**Comment by stojsavljevic** [comment]
Ah OK, if we got the the maven config earlier we could reproduce this easily.
Also, I expected that build fails in this case.

Anyway, I'll take a look but it should be safe to keep the value on `false`. In that case only POJOs that are actually used in generated code will be generated.
In the above example `HttpProblem` object will not be generated since it's only used in 404 declaration for which we don't generate Spring code.

**Comment by stojsavljevic** [comment]
It seems that `generateUnreferencedSchemas` works for json schemas only and not for data types.
So I'll either fix that or state it in the README file.

**Comment by stojsavljevic** [comment]
`generateUnreferencedSchemas` is renamed `generateUnreferencedObjects` and it works for data types as well.
