### ISSUE TITLE
Plugin generates equals() method that always returns true after it passes the checks by reference and instance of

### ISSUE THREAD

**Issue by bbd127** [phoenixnap/springmvc-raml-plugin#178]
Hello,

I've encountered an issue with this plugin and it's generation of _equals()_ method in generated model classes. Here is an example:

    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof MyResource) == false) {
            return false;
        }
        MyResource otherObject = ((MyResource) other);
        return new EqualsBuilder().isEquals();
    }

Once the method is past the check by reference and _instance of_ check it will always return true if there are no fields appended to the builder. 

I'm already patching this up to provide _equals()_ and _hashCode()_ methods that will be generated via reflection support from EqualsBuilder and HashCodeBuilder:

    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof MyResource) == false) {
            return false;
        }
        MyResource otherObject = ((MyResource) other);
        return EqualsBuilder.reflectionEquals(this, otherObject);
    }

This is the fastest and simplest patch I can do for the issue. The downsides are performance and  _AccessibleObject.setAccessible_ that _reflectionEquals()_ uses to gain access to private fields. It will throw a security exception if run under a security manager, if the permissions are not set up correctly.

Another approach that could be taken is to append non transient and non static fields through EqualsBuilder like:

        return new EqualsBuilder()
                .append("field1", field1)
                .append("field2", field2)
                ....
                .isEquals();

But that will take more time to implement.

Please let me know if I can pick this up and apply the 1st solution for now.

Regards,
Slaviša

**Comment by stojsavljevic** [comment]
Closed with #179
