### ISSUE TITLE
Spring->RAML  conversion without source code(ie if input is a jar/war file)

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#18]
We are trying to read Spring MVC project to get a RAML file.
Below are the considerations:-
-our war file will be inclusive of Controllers and other java files.
-they could be compiled using different build tools i.e. IVY,Maven

Please let us know if this Spring->RAML plugin can  resolve this issue.
Below are our findings.
When it comes to reading a jar or a war file ,the generated RAML only has content hat is generated from the  pom.xml file .
but it does not have any other content like request,response.

**Comment by kurtpa** [comment]
The source code is only required for the documentation (descriptions etc). The reason for this is that all javadoc is not included in the class files.

Other structures which are loaded by reflection will be detected if the classes are loaded on the classpath.

When it comes to WAR files make sure to run the plugin in a maven phase that is post compilation but before the war is built.

From: rahulkamuni
Sent: Wednesday, 2 March, 14:41
Subject: [springmvc-raml-plugin] Spring->RAML  conversion without source code(ie if input is a jar/war file) (#18)
To: phoenixnap/springmvc-raml-plugin

We are trying to read Spring MVC project to get a RAML file.
Below are the considerations:-
-our war file will be inclusive of Controllers and other java files.
-they could be compiled using different build tools i.e. IVY,Maven

Please let us know if this Spring->RAML plugin can resolve this issue.
Below are our findings.
When it comes to reading a jar or a war file ,the generated RAML only has content hat is generated from the pom.xml file .
but it does not have any other content like request,response.

-

**Comment by kurtpa** [comment]
Is this solved or do you require anything else?

**Comment by rahulkamuni** [comment]
issue

**Comment by rahulkamuni** [comment]
Thanks for your reply.
No issue is not resolved. 
My requirement is to convert springMVC ( using IVY.xml) to RAML .
Below are my requirement 
A) I have spring MVC project of using build tool  "IVY.xml"
B) As your "springmvc-raml-plugin" is using maven project so how should I add all jars of ivy.xml to maven project ?
C) As I have seen your code  internally it is using reflection. I am not add war file as dependency.

**Comment by kurtpa** [comment]
Adding WAR as a dependency is usually not a good idea. I think your best bet in this case would be to either:
1. Move the build of the war to Maven, and then just add this plugin to your build (you will be in the actual project so you wont need to add it as a dependency.
or 2. skip maven entirely. The code which generates/parses Spring & RAML is a standalone component, which can be triggered using an Ivy mechanism? or at runtime.

If you take a look at the generateRaml method of the SpringMvcRamlApiSyncMojo it's doing the work - you would need to make sure the controllers are available at runtime or in the 

From our end, integration with Ivy is not on our roadmap.

**Comment by rahulkamuni** [comment]
Thanks for your suggestion.
I am planning to create a standalone component which can triggered from IVY.
If you don't you mind do you have code snippet of standalone component otherwise i will remove maven manually from code by finding its reference. i.e Deleting all reference of MOJO.

**Comment by kurtpa** [comment]
Check out generateRaml() - line 100 on this class: https://github.com/phoenixnap/springmvc-raml-plugin/blob/master/springmvc-raml-plugin/src/main/java/com/phoenixnap/oss/ramlapisync/plugin/SpringMvcRamlApiSyncMojo.java

It shows how to instantiate the SpringMvcResourceParser and send the output to a file

**Comment by rahulkamuni** [comment]
Thanks Kurtpa for your reply.
I have one question.
1)  In my spring MVC project I have one delete operation accepting one bean(POJO) object as parameter. 
After generating RAML of above delete operation.In generated RAML delete operation is not accepting any bean(POJO) object as request schema.
Do you have any suggestion for that ?

**Comment by kurtpa** [comment]
Due to some complications with DELETE and RequestBody (http://stackoverflow.com/questions/25375046/passing-data-in-the-body-of-a-delete-request) - also in my personal opinion (i could be wrong) but passing lots of data in DELETEs is a bit of an anti pattern, i had only supported request bodies in PUT and POST. In fact certain implemetations may strip this data at runtime or fail to parse it.

If you must support this in the plugin check out https://github.com/phoenixnap/springmvc-raml-plugin/blob/46be551b39c359c732c9b2b339c9fe43db5ddee8/springmvc-raml-parser/src/main/java/com/phoenixnap/oss/ramlapisync/parser/ResourceParser.java#L109  and just add DELETE to the list of methods supporting bodies.

I will add this as a feature in 0.2.5 or 0.3.x unless you want to submit a PR :)

**Comment by rahulkamuni** [comment]
Thanks. Let me check. 
Awesome code you have written. Easily configurable. 
Good..

**Comment by kurtpa** [comment]
Thank you :)

**Comment by kurtpa** [comment]
Closing issue - if you need any other support just let me know. Created issue #21 to allow configuration of request bodies
