### ISSUE TITLE
Issue generating POJOs from RAML with array type inheritance

### ISSUE THREAD

**Issue by agluquetc** [phoenixnap/springmvc-raml-plugin#199]
Hi,
First of all, congratulations for this **awesome** job. 

We are using the plugin in order to generate our models based on a raml file. We have a raml file like this:
```
#%RAML 1.0
title: TEST API
version: v1
baseUri: /api/{version}

types:
  Employee:
    properties:
      name: string
      skill: string

  EmployeeExtended:
    type: Employee
    properties:
      job: string

  EmployeeRq:
    properties:
      employees: Employee[]

  EmployeeRs:
    properties:
      employees: EmployeeExtended[]

/employee:
  post:
    body:
      application/json:
        type: EmployeeRq
    responses:
      200:
        body:
          application/json:
            type: EmployeeRs
```
The plugin generate the following classes:
`Employee`
`EmployeeRq`
`EmployeeRs`

The class `EmployeeExtended` is not generated and the class `EmployeeRs` is not properly generated (it created a simple POJO without the generic collection):
```
public class EmployeeRs implements Serializable
{

    final static long serialVersionUID = -6814991346091494838L;
    @NotNull
    private Employee employees;
...
```
Checking the code, we noticed that it can be solved applying some changes in the array interpreter class when the class was already handled previously and it is already present in the builder model from JcodeModel.

I will create a pull request with the suggested changes.

**Comment by stojsavljevic** [comment]
Thanks for finding this and getting in touch.

Yes, check `ArrayTypeInterpreter` but also `ObjectTypeInterpreter` and `RamlTypeHelper`.

Thanks.
