### ISSUE TITLE
commons-lang3

### ISSUE THREAD

**Issue by emichaf** [phoenixnap/springmvc-raml-plugin#202]
Is springmvc-raml-plugin compatible with:

            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.5</version>

?

**Comment by stojsavljevic** [comment]
Yes, you just need to use `useCommonsLang3` config option.
Something like:
```
...
<rule>com.phoenixnap.oss.ramlapisync.generation.rules.Spring4ControllerDecoratorRule</rule>
<generationConfig>
	<useCommonsLang3>true</useCommonsLang3>
</generationConfig>
...
```

**Comment by emichaf** [comment]
Thnx!
