### ISSUE TITLE
Problem with array of type

### ISSUE THREAD

**Issue by ponticello89** [phoenixnap/springmvc-raml-plugin#205]
I generated the code from:

```
types:
  Car:       
    properties:      
      colors:
        type: Color
  Color:
    properties:
      name:
        type: string        

/cars:  
  get:   
    responses:
      200:
        body:          
          type: array
          items: Car          
/colors:  
  get:   
    responses:
      200:
        body:          
          type: array
          items: Color
```

I'm getting an issue in the colors api, the controller generated is this:

`public ResponseEntity<Color> getColors();`

the return is an Object type Color rather than being a `List<Color>`.
By some investigation I confirmed that the issue is coming from the fact that I'm using Color as a property in Car

**Comment by looser990** [comment]
I'll be taking care of this (Marjan).

**Comment by looser990** [comment]
We can confirm this one is fixed with newest `master` branch of the plugin. Tested both with
`Color[]` and with:
```
body:
          application/mercury-api.v.1+json:
            type: array
            items: Color
```
Thanks!
