### ISSUE TITLE
Spring MVC to RAML .(Is there any way to add request parameter schema in RAML which is not annotated by "@RequestBody")

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#22]
We are trying to generate RAML from Spring MVC.
In my Controller I have a method (API) which has a request parameter as an argument and for which it is not annotated by "@RequestBody".
So In RAML the schema of request parameter is not getting generated. 
Is there any way to add that parameter schema in RAML?

**Comment by kurtpa** [comment]
Could you paste a code snippet?

Since there could be many parameters in the request (some of which are things like HttpServletRequest) i don't think you can just omit the @RequestBody entirely. I've never done this before - not sure how Spring reacts :)

**Comment by kurtpa** [comment]
After some internal discussion, since the spring best practice asks for the @RequestBody and other parameters may exist in the method that will not need to be generated from, we wont be adding this feature to the plugin for now.
