### ISSUE TITLE
Can support raml1.0? [Java to RAML]

### ISSUE THREAD

**Issue by lanmolsz** [phoenixnap/springmvc-raml-plugin#223]
I saw a lot of raml1.0 has been completed, and if I want to improve it, What should I do? Who can guide me?

**Comment by stojsavljevic** [comment]
Hi @lanmolsz 

Thanks for getting in touch.

I want to restructure the plugin and when it's ready I will get in touch with you.
I already started the work, you can track it here: https://github.com/phoenixnap/springmvc-raml-plugin/projects/1
New and old versions will leave together on dedicated branches.
But keep in mind that Java -> RAML path is not my top priority.
I enforce RAML -> Java as part of contract-first approach.

Anyway, as soon as I have some tangible task - I'll inform you.
