### ISSUE TITLE
publish to mvnrepository.com

### ISSUE THREAD

**Issue by JavaChr1s** [phoenixnap/springmvc-raml-plugin#229]
Hi,

This is a really cool plugin. Thanks for developing it!

Could you maybe publish the actual version at mvnrepository.com ? I would like to get https://github.com/phoenixnap/springmvc-raml-plugin/commit/95c29e019bd216aa4504ce420fda852c5e580b49 

Thank you

**Comment by stojsavljevic** [comment]
It's released as `0.10.13`. In a day or two it will be on mvn repo.
