### ISSUE TITLE
Migration to Spring Boot 2.x.x

### ISSUE THREAD

**Issue by rushua** [phoenixnap/springmvc-raml-plugin#244]
Spring Boot 2.x.x requires Spring Cloud 2.x.x
Details: http://projects.spring.io/spring-cloud/

New version of Spring Cloud OpenFeign was switched to new FeignClient namespace:
org.springframework.cloud.openfeign.FeignClient
Details: https://cloud.spring.io/spring-cloud-openfeign/

Generation results are not compiled.

I created my own rules for old plugin version and resolve this case.
But it will be nice to have it fixed in next build. Thanks.

**Comment by tburny** [comment]
https://github.com/phoenixnap/springmvc-raml-plugin/pull/296/files
This pull request fixes the package and updates to Spring Boot 2 :)

**Comment by stojsavljevic** [comment]
Implemented with #296

**Comment by tburny** [comment]
We should reopen this as long as it is not in 2.10.0

**Comment by stojsavljevic** [comment]
It is on master. It wasn't part of `2.0.5` but will be a part of `2.1.0`.

**Comment by paulius-p** [comment]
Is there any ETA when this is going to be released?
