### ISSUE TITLE
In Generated RAML from Spring MVC ( In Query Parameter all argument are coming as arg0 , arg1 etc)

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#25]
I have generated RAML from Spring MVC.
In my controller I have GET operation with @RequestParam as argument.
After generating RAML in "queryParameters" I am getting arg0,arg1,arg2  instead of actual parameter.
After searching some stuff on google I got a solution that  it is related to some java version issue.
For more details please find the attachment of QueryParamter.
![queryparmeter_missing](https://cloud.githubusercontent.com/assets/15646381/13808811/e7a3a186-eb8d-11e5-899e-8200d3feb8b5.PNG)

Please check below links:
http://stackoverflow.com/questions/26056131/get-parameter-names-in-a-method-using-reflection

**Comment by kurtpa** [comment]
This duplicates issue #24  - same resolution applies. you need to compile your code using Java 8 using the -parameters option. There is no other solution at present and we will not be supporting alternate solutions with older java versions.

To store formal parameter names in a particular .class file, and thus enable the Reflection API to retrieve formal parameter names, compile the source file with the -parameters option of the javac compiler. (Source: oracle)
