### ISSUE TITLE
Add possibility to use Java Time instead of java.util.Date

### ISSUE THREAD

**Issue by piffta** [phoenixnap/springmvc-raml-plugin#253]
Please add an option to be able to use Java Time instead of `java.util.Date`.

**Comment by stojsavljevic** [comment]
Now you can use `generationConfig` to configure desired date and time types.
Example config:
```
<configuration>
	...
	<generationConfig>
		...
		<dateTimeType>java.time.ZonedDateTime</dateTimeType>
		<dateType>java.time.LocalDate</dateType>
		<timeType>java.time.LocalTime</timeType>
	</generationConfig> 
</configuration>
```

This applies to data types, query and uri parameters and headers.
