### ISSUE TITLE
Option to skip headers in method parameters when using injectHttpHeadersParameter

### ISSUE THREAD

**Issue by techpavan** [phoenixnap/springmvc-raml-plugin#254]
It might remove a lot of clutter in the method signature if there is an option to skip adding individual headers as method parameters when headers object is added in the parameter.

**Comment by stojsavljevic** [comment]
Hi,
Why would you want to exclude a header as method parameter?
If you want to ignore it - why do you define it?

**Comment by techpavan** [comment]
Its not like ignoring, but the same value is provided twice as method parameters, one as individual param and other as a part of headers. When too many headers are defined, the method length would be too high which might not look good.

**Comment by techpavan** [comment]
That's right. And that's what I actually meant, not sure if my choice of words gave a different meaning.

**Comment by techpavan** [comment]
That would work well. There is no need of headers individually when all headers are available.
