### ISSUE TITLE
Problem with finding generated Class

### ISSUE THREAD

**Issue by Boskiantonio** [phoenixnap/springmvc-raml-plugin#32]
For example raml file : 
```xml
#%RAML 0.8
baseUri: https://api.example.com
title: Filesystem API
version: 0.1
mediaType:  application/json
schemas:
  - Www: |
      {
        "type": "object"
      }
/files:
  post:
    displayName: Create file
    description: Create file.
    body:
      application/json:
        schema: Www
    responses:
      201:
        description: file was created.
        headers:
          Location:
            type: string
            required: true
            example: /file/bd2907ea-5f86-11e5-9d70-feff819cdc9f
        body:
          application/json:
            schema: Www
```

and plugin configuration

```xml
				<configuration>
					<ramlPath>raml/gymbook.raml</ramlPath>
					<outputRelativePath>/src/generated</outputRelativePath>
					<addTimestampFolder>false</addTimestampFolder>
					<basePackage>com.gen.wow</basePackage>
					<baseUri>/api</baseUri>
					<seperateMethodsByContentType>false</seperateMethodsByContentType>
				</configuration>
```

generate-springmvc-endpoints during maven compilation returns:
`
generate-springmvc-endpoints failed: No unique class found for simple class name Www -> [Help 1]
`

As far as i can see method CodeModelHelper.findFirstClassBySimpleName is trying to find POJO class in com.gen.wow instead of com.gen.wow.model. Class Www exists in model package and have no fields.

**Comment by kurtpa** [comment]
Checking for you :)

**Comment by kurtpa** [comment]
Thanks for bringing this up! :) Fixed on Master. This will be released with 0.4.2 in the coming days.

**Comment by Boskiantonio** [comment]
Great ;) But Pojo class is still empty. There is no "type" field inside.

**Comment by kurtpa** [comment]
In your schema, you are defining the type as object, however you are not defining any fields. The plugin uses the jsonschema2pojo project (http://www.jsonschema2pojo.org/) and this is the class that will be generated for the schema you specified.

**Comment by Boskiantonio** [comment]
Crap my bad. Didn't notice that i removed json body during testing. Thx!

**Comment by kurtpa** [comment]
No worries :) you had me worried there for a sec :)

**Comment by kurtpa** [comment]
0.4.2 is now up on maven central :)
