### ISSUE TITLE
property: 'RAML' is invalid in a body

### ISSUE THREAD

**Issue by n614cd** [phoenixnap/springmvc-raml-plugin#35]
I am generating the RAML from a Spring RestContoller.
The generated RAML has the following syntax inserted into it:
......
            description: changePassword
            body: 
                RAML: 
                    schema: |
                        {
                          "type" : "object",
.....

From what I can find and see in other examples, the RAML tag is invalid and should not be present. The RAML Console also provides an error on the body tag.

**Comment by kurtpa** [comment]
Could you kindly provide an example of your code and mvn configuration so that we can troubleshoot please

**Comment by n614cd** [comment]
I am using Gradle. Here is the gradle code calling the generator:
`	protected File projectBase = new File(".");
	protected String version = "0.0";
	protected String defaultMediaType = "application/json";
	protected String webAppName = "/aw-api/";
	protected Set<ApiDocumentMetadata> documents = null;
	
	protected void generate() throws IOException {		
		ResourceParser scanner = new SpringMvcResourceParser(projectBase, version, defaultMediaType, false);
		RamlGenerator ramlGenerator = new RamlGenerator(scanner);
		// Process the classes selected and build Raml model
		ramlGenerator.generateRamlForClasses(getTitle(), version, webAppName, getClassList(), documents);
		File out = new File(getOutputLocation());
		if (out.exists()) out.delete();
		ramlGenerator.outputRamlToFile(getOutputLocation(), true, false);
	}

	protected Class<?>[] getClassList() {
		// now use reflections to get all the classes
		ArrayList<Class<?>> list = new ArrayList<Class<?>>();
		
		String[] pkgs = getPackageList();
		for (String pkg : pkgs) {
			Reflections reflections = new Reflections(pkg);
			Set<Class<?>> annotated = reflections.getTypesAnnotatedWith(RestController.class);			
			list.addAll(annotated);
		}
		
		// now convert to an array
		Class<?>[] result = new Class<?>[list.size()];
		for (int ptr=0; ptr < list.size(); ptr++) {
			result[ptr] = list.get(ptr);
		}
		return result;
	}
	protected abstract String getTitle();
	protected abstract String getOutputLocation();
	protected abstract String[] getPackageList();
`
and a partial class performing the rest services:
`@RestController
public class TrancentivesAPI extends DataValidation {

	@Autowired
	IRateService rateService;

	@Autowired
	IMerchantProfileService merchantProfileService;

	@Autowired
	ICustomerAccountService customerAccountService;

	// public ResponseEntity<?> changePassword(@RequestBody
	// ChangePasswordRequest changePasswordRequest) throws
	// AuthenticationException {

	@SuppressWarnings("unchecked")
	@RequestMapping(AWContexts.TRANCENTIVES.MERCHANT + "queryByName")
	@PreAuthorize("hasAuthority('QUERY_MERCHANT')")
	public ResponseEntity<MerchantResponse> queryMerchantForKey(@RequestBody MerchantRequest merchantRequest) {
		MerchantProfile profile = merchantProfileService.getByName(merchantRequest.getName());
		if (profile != null) {
			MerchantResponse response = new MerchantResponse();
			response.setKey(profile.getPrimaryKey());
			response.setName(profile.getName());
			response.setProcessorRateFee(profile.getProcessorRateFee());
			response.setBaselineRate(profile.getBaselineRate());
			response.setBaselineMethod(profile.getBaselineMethod());
			return ResponseEntity.ok(response);
		} else {
			return (ResponseEntity<MerchantResponse>) ResponseEntity.notFound();
		}
	}
}
`

**Comment by kurtpa** [comment]
The RAML: entry you are seeing is being inserted as a media type for the request body. Based on the code you posted, I'm expecting to see the defaultMediaType value in there. I'll check to see if I can replicate the issue

**Comment by n614cd** [comment]
I have since added a defaultMediatype, and made multiple other changes. I know longer get the RAML text; but I do not know what change eliminated it. Good luck, Tim

**Comment by kurtpa** [comment]
I suspect that the generator is relying on a default value that might have been lost in translation in the gradle driver. If so I need to make the generator throw an exception and not produce the RAML output. Just to confirm - did you have defaultMediaType = RAML at any point?

**Comment by n614cd** [comment]
No on defaultMediaType = RAML.
I initially had the value equal to null; but at some point changed it. Not sure when the issue went away.

**Comment by kurtpa** [comment]
Oki will check it out :)

**Comment by kurtpa** [comment]
The only way i was able to replicate this is by explicitly putting "RAML" as a data type - either as default MediaType or within the Spring annotations. I tried using null or "" and it just ends up as a null in the model and fails to generate the file. I'm going to be closing this issue for now, if you or anyone else can replicate this i'll be happy to see and fix it
