### ISSUE TITLE
RequestMapping

### ISSUE THREAD

**Issue by n614cd** [phoenixnap/springmvc-raml-plugin#36]
Walking the code, there seems to be a fundamental assumption that classes are annotated with a RequestMapping, and then methods have a second annotation to further define the path. 
However this does not seem to be documented.

**Comment by kurtpa** [comment]
That is correct, but that is the way spring works. Unless we have regressed, the plugin can deal with cases where 1 or both annotations are present.

**Comment by n614cd** [comment]
Sorry, I should have been more clear. I did not do class level annotations initially, and in fact most people I know do not. My normal process is to only do them at the method level; often because the rest controller is rather thin with the majority of code in the service tier.

**Comment by kurtpa** [comment]
That's not a problem, however since Spring MVC allows annotations at both levels, the plugin must be able to extract and combine both. We don't require both though, method level alone should work :)
