### ISSUE TITLE
Support for baseUri during Spring generation and check

### ISSUE THREAD

**Issue by tsarnowski** [phoenixnap/springmvc-raml-plugin#37]
Hi
I have following raml file
#%RAML 0.8
---
title: Sample API
baseUri: http://127.0.0.1/rest/{version}
version: v1
mediaType: application/json
                
/homologations:
  /{commisionNumber}:
Generated Spring endpoint:
@Controller
@RequestMapping(value = "/api/homologations", produces = "application/json")
public class HomologationController {

I think that RequestMapping value should be generated based on baseUri. 
In addition when i want to verify my code against raml file i get error
Expected resource missing: /homologations in SOURCE
So it is some inconsistency in project development flow in my opinion 
I use version 0.4.2

**Comment by kurtpa** [comment]
based on the code you pasted, the raml is defining that your endpoint is "/homologations", whereas in the spring controller your mapping is defining "/api/homologations". This correctly causes the plugin to break the build in verification mode since the urls you define in the RAML are not found in the spring code.

In general baseUri is ignored for verification since this should be agnostic to the application (and subsequently the published raml file).

The correct RAML for the api you are defining in that controller would be:
    /api:
       /homologations:

**Comment by tsarnowski** [comment]
You are right using baseUri is not good idea.
But in my project I have other parts than API so I would like to add URI prefix to API methods specified in raml file. This way I will be able to handle multiple APIs and separate them from other code on URI level. 
So maybe You agree to add configuration parameter to prefix generated endpoint URI`s? I You agree I can do that modification and provide merge request.

BTW
The other problem is that in my example I generated  spring code from raml and then wanted to check that code against raml file. I didn`t make any changes in generated code. I wondering why generated endpoint have "/api" prefix?

**Comment by kurtpa** [comment]
Could you provide the configuration you used to generate the Spring code from the RAML? I suspect you added the <baseUri>/api</baseUri> to your configuration. This will add that portion of the URL to the generated @RequestMapping urls.

If i'm understanding correctly this will work for what you want to achieve right?

**Comment by tsarnowski** [comment]
Below is my configuration and raml file
[conf.txt](https://github.com/phoenixnap/springmvc-raml-plugin/files/251569/conf.txt)
[raml.txt](https://github.com/phoenixnap/springmvc-raml-plugin/files/251570/raml.txt)
Even if I change baseUri parameter to "/" i can`t gerate sources and check with success.

**Comment by kurtpa** [comment]
I tried to replicate your issue, 

i set baseUri to "/" in generation and i got the following output which worked:
```

package pl.unity.drive.rest;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import pl.unity.drive.rest.model.GetHomologationsResponse;


/**
 * No description
 * (Generated with springmvc-raml-parser v.0.4.2)
 * 
 */
@Controller
@RequestMapping(value = "/homologations", produces = "application/json")
public class HomologationController {


    /**
     * No description
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    @ResponseBody
    public GetHomologationsResponse getHomologations() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

}
```

**Comment by kurtpa** [comment]
keep in mind that the default behaviour of the plugin is that it is not deleting any existing code so you will need to manually delete the classes that were generated before. I'm adding an issue to allow overwrites if configured

**Comment by tsarnowski** [comment]
I got same java code, but when I try to verify that code I got error: missing /homologations in source.
Did you try check generate code agains raml file?

**Comment by kurtpa** [comment]
yes i used the same configuration you used.

I would suggest that you delete the generated code manually and try again, maybe something is left behind that is causing a conflict?

**Comment by tsarnowski** [comment]
I try also with deleting generated code. Below is interesting parts of verify log:

[INFO] Scanning package pl.unity.drive.rest
[INFO] Scanning package pl.unity.drive.rest.model
....
[INFO] Generating Raml for drive-web v1 from 0 annotated classes
[INFO] Performing Resource and Action Visitor Checks
[INFO] Performing Resource Existence Checks
[ERROR] Expected resource missing: /homologations in SOURCE
[ERROR] Issue [severity=ERROR, location=SOURCE, type=MISSING, description=Missing Resource., ramlLocation=/homologations]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by kurtpa** [comment]
Are you running both generation and verification in the same build? Because this could be an issue of ordering. Try them in separate builds

**Comment by tsarnowski** [comment]
I use separate profiels and run it separately - during one build I only run one phase.

**Comment by kurtpa** [comment]
Here is the result of my execution of:

-PgenerateRestApiEndpoints
```
[INFO] --- springmvc-raml-plugin:0.4.2:generate-springmvc-endpoints (generate-springmvc-endpoints) @ springmvc-raml-tester ---
pl\unity\drive\rest\model\GetHomologationsResponse.java
pl\unity\drive\rest\HomologationController.java
[INFO] Endpoint Generation Complete in:307ms
```

-PcheckRestApiSpec:
```
[INFO] --- springmvc-raml-plugin:0.4.2:verify-springmvc-api-docs (generate-springmvc-api-docs) @ springmvc-raml-tester ---
2016-05-06 14:12:15 INFO [plugin.ClassLoaderUtils] - Loading packages in d:\Workspace\PluginTest\src\main\java...
[INFO] Scanning package pl
[INFO] Scanning package pl.unity
[INFO] Scanning package pl.unity.drive
[INFO] Scanning package pl.unity.drive.rest
[INFO] Scanning package pl.unity.drive.rest.model
2016-05-06 14:12:15 INFO [generation.RamlGenerator] - Generating Raml for springmvc-raml-tester v1 from 1 annotated classes
2016-05-06 14:12:15 INFO [parser.ResourceParser] - Parsing resource: HomologationController
2016-05-06 14:12:15 INFO [parser.SpringMvcResourceParser] - Added call: /homologations/ GET from method: getHomologations
2016-05-06 14:12:16 INFO [checkers.RamlCheckerResourceVisitorCoordinator] - Performing Resource and Action Visitor Checks
2016-05-06 14:12:16 INFO [checkers.ResourceExistenceChecker] - Performing Resource Existence Checks
[INFO] Raml Generation Complete in:638ms
```
And here is the maven configuration file as well as the output controller:
[maven-config.txt](https://github.com/phoenixnap/springmvc-raml-plugin/files/252136/maven-config.txt)

[HomologationController.java.txt](https://github.com/phoenixnap/springmvc-raml-plugin/files/252138/HomologationController.java.txt)

**Comment by tsarnowski** [comment]
Please, could You provide maven version and full command You run ?

**Comment by kurtpa** [comment]
Maven 3.0.5 & 3.2.5

mvn clean install -PgenerateRestApiEndpoints
mvn clean install -PcheckRestApiSpec

**Comment by tsarnowski** [comment]
I commented out execution phase co not all classes was available to the plugin.
Thanks a lot for Your help.
