### ISSUE TITLE
[RAML Verification]  Support for uriPrefix during verify-springmvc-api-docs

### ISSUE THREAD

**Issue by tsarnowski** [phoenixnap/springmvc-raml-plugin#39]
When I generated code form RAML using baseUri parameter other than "/" then I have problems with check implementation against source RAML file.
I believe that that is right way to develop APIs so I prepare sample solution #38 . I`m not sure if that is best way to achieve  my goal but it work.
@kurtpa Do You agree to merge this change ?

**Comment by kurtpa** [comment]
The code is complete in feature branch /feature/ignore-uri-prefix - Could you try it locally and see if it satisfies your requirements please? If so i will release this in 0.5.3 over the weekend

**Comment by kurtpa** [comment]
Apologies - i had forgotten to push the code to github. 0.5.3 is now committed and if there are no problems i will be merging and closing this issue over the weekend

**Comment by tsarnowski** [comment]
I`ve checked in my project and it works properly.
Thank You for fast implementation.
