### ISSUE TITLE
Support of jsonschema2pojo configuration

### ISSUE THREAD

**Issue by ellavas** [phoenixnap/springmvc-raml-plugin#45]
Hi,

When using the JsonSchema2Pojo maven plugin, it's possible to generate pojo based a specific configuration. (for example, use of BigDecimal, commons lang 3, date type...).
I have tried your plugin to generate endpoints and pojo from the raml, and I notice that the configuration is very limited for now (use of Long).
Would it possible to enhance the configuration of your maven plugin ?

Thanks,
Sebastien

**Comment by kurtpa** [comment]
It's on my to-do list but will be a while. If you wish to follow the existing convention feel free to extend and submit a PR :)

**Comment by ellavas** [comment]
Ok we'll work on that topic and submit a pull request.

**Comment by ellavas** [comment]
Do you have any idea regarding the availability of the 0.6.0 ?

**Comment by kurtpa** [comment]
Latest by Sunday. More likely today evening or tomorrow :)

**Comment by ellavas** [comment]
:+1:
