### ISSUE TITLE
add support of resources with underscores

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#50]
Hi,

In a project we are defining resources with lowercase and underscores.
After trying to use the plugin to generate the endpoint, it appears that json models are correctly written but controllers:

A schema named `sample_unit.json` will be converted to an object named `SampleUnit.java`.

But it will not be the case for controllers : 
The plugin will generate a class named `Sample_unitController` with references to non existing objects.

The raml snippet:
```raml
/sample_units:
  displayName: Samples
  description: A collection of samples
  get:
    description: Retrieves samples
    responses:
      200:
        description: The sample unit collection has been successfully retrieved.
        body:
          application/json:
            schema: sample_units
...
```
The resulting Controller snippet:
```java 
   /**
     * Retrieves samples
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    public ResponseEntity<List<Sample_unit>> getSample_units();
```

Will it be possible to adapt the code generator to rename object references in camel case ?

Thanks,
Mehdi.

PS: You can find here a modified example to expose my issue: https://github.com/mehdijouan/springmvc-raml-plugin-sample

**Comment by kurtpa** [comment]
Looks like a bug :)

**Comment by kurtpa** [comment]
doh looks like we were working on it at the same time - i used a similar approach but relied on jsonschema2Pojo's name generation so that we will be more in line just in case they are doing something different. i'm committing to master - if this doesnt give you the expected behaviour let me know :)

**Comment by mehdijouan** [comment]
it works well, thanks for the fix. 
Do you have an idea of when the version 0.5.4 will be available on maven repositories ?

**Comment by kurtpa** [comment]
Later on today :)

**Comment by mehdijouan** [comment]
perfect 👍
