### ISSUE TITLE
Code generation fails using top level array in response

### ISSUE THREAD

**Issue by mbs99** [phoenixnap/springmvc-raml-plugin#55]
Hi,

code generation fails when using a schema referencing another json file.

RAML:

`schemas: 
-list: list.json`
...
`responses:
      200:
        body:
          application/json:
            schema: list`

list.json:

`{
 "type": "array",
 "additionalProperties": false,
 "items": {
   "$ref": "types.json#/definitions/BaseType"
 }
}`

The controller method references an unknown list object type, which is not generated.
`public ResponseEntity<List<BaseTypeResponse>> getList()`
There's no need for an new object instead of
`List<BaseType>`

**Comment by kurtpa** [comment]
Hmmm, ya this looks like it could be improved. i'll try take a look at it over the weekend

**Comment by kurtpa** [comment]
Are you using the schemaLocations  configuration in the pom to add types.json to your classpath?

**Comment by mbs99** [comment]
yes
`<schemaLocation>src/main/resources</schemaLocation>`

**Comment by kurtpa** [comment]
oki i'll try replicate this problem soon... (and fix it ;) long flight coming up :) if you have a code snippet handy i'll use that for replication

**Comment by kurtpa** [comment]
The issue here is that there is no explicit name and we currently are unable to infer the name of the schema. Jsonschema2pojo can use a "javaType" to use as the name for the generated class and I've added support for the plugin to detect this case. Unfortunately $ref support is not exhaustive at present
