### ISSUE TITLE
Media Types defined at Method level are ignored during class generation

### ISSUE THREAD

**Issue by Leroy14** [phoenixnap/springmvc-raml-plugin#58]
Hi,

If the media type is defined at the top level of the RAML file then the corresponding Java controller will be annoted with an annotation configured with this media type.
For example for the following raml ...
```raml
#%RAML 0.8
title: xxx API
version: v1.0
baseUri: /
mediaType:  application/json
...
/xxx:
```
here is how annoted the corresponding Java controller is:
```java
@RestController
@RequestMapping(value = "/xxx", produces = "application/json")
```
All is ok !
Now if in the raml, I defined a media type at the method level, for example:
```raml
  post:
    body:
      application/json:
        schema: xxx
    responses:
      201:
        body:
          text/plain:
```
The corresponding method of the controller is not annoted with the media type 'produces' as expected. I would expect the method annotation RequestMapping is initialized with the 'produces' and 'consumes' media types.

Looking in the code, the class 'SpringRequestMappingMethodAnnotationRule' that generates the method annotations use only the 'value' and 'method' properties of the provided 'ApiMappingMetaData'.

It would be nice to always provide the media type (when specified) at the method level by updating the following code: 
```java
public class SpringRequestMappingMethodAnnotationRule implements Rule<JMethod, JAnnotationUse, ApiMappingMetadata> {
   @Override
   public JAnnotationUse apply(ApiMappingMetadata endpointMetadata, JMethod generatableType) {
      final JAnnotationUse requestMappingAnnotation = generatableType.annotate(RequestMapping.class);
      requestMappingAnnotation.param("value", endpointMetadata.getUrl());
      requestMappingAnnotation.param("method", RequestMethod.valueOf(endpointMetadata.getActionType().name()));
      return requestMappingAnnotation;
   }
``` 
by
```java
public class SpringRequestMappingMethodAnnotationRule implements Rule<JMethod, JAnnotationUse, ApiMappingMetadata> {
   @Override
   public JAnnotationUse apply(ApiMappingMetadata endpointMetadata, JMethod generatableType) {
      final JAnnotationUse requestMappingAnnotation = generatableType.annotate(RequestMapping.class);
      requestMappingAnnotation.param("value", endpointMetadata.getUrl());
      requestMappingAnnotation.param("method", RequestMethod.valueOf(endpointMetadata.getActionType().name()));
      requestMappingAnnotation.param("produces", endpointMetadata.getProduces());
      requestMappingAnnotation.param("consumes", endpointMetadata.getConsumes());
      return requestMappingAnnotation;
   }
```
Note: Not sure if endpointMetadata.getProduces() can return null, otherwise this must be checked before the invocation.

Hope it is meaningful for you!
Best Regards,

**Comment by kurtpa** [comment]
Sounds interesting,  would you be interested in submitting a PR for this?

**Comment by Leroy14** [comment]
After reading the purpose of Media Type, I do not consider my use case as valid anymore because the same method would have to return sometime json, sometime txt and that make the method generation difficult (which return type must be used). Another option would be to create to method and let the caller defining its preferred media type but in this case the implementation of the method will be artificially more complex.
I will change my media type to json and continue to use your pluggin as it is.

**Comment by kurtpa** [comment]
Or we could generate 1 method for each different return content type
