### ISSUE TITLE
Incompatibility error while maven executing goals 

### ISSUE THREAD

**Issue by tausiflife** [phoenixnap/springmvc-raml-plugin#60]
[ERROR] Failed to execute goal com.phoenixnap.oss:springmvc-raml-plugin:0.6.1:generate-springmvc-endpoints (generate-springmvc-endpoints) on project raml-to-java: A type incompatibility occured while executing com.phoenixnap.oss:springmvc-raml-plugin:0.6.1:generate-springmvc-endpoints: org.yaml.snakeyaml.nodes.ScalarNode cannot be cast to org.yaml.snakeyaml.nodes.MappingNode
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.phoenixnap.oss:springmvc-raml-plugin:0.6.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

How to solve this?

**Comment by kurtpa** [comment]
Off the cuff it looks like you have errors in your raml file. Having said that there is far too little info here.

**Comment by tausiflife** [comment]
I am able to generate raml-to-java(with javax.ws package) files so i don't think my raml has errors. Let me know what all files you need so solve this.

**Comment by kurtpa** [comment]
At the very least the raml you are trying to parse and the maven configuration of the plugin

**Comment by tausiflife** [comment]
#%RAML 0.8
title: StopCheque API
baseUri: http://eds-digital.rbs.com/{version}
version: v0.1

schemas:
  - request: !include sc-request.schema
  - stopCheque: !include sc.schema
  - exception: !include exception.schema
  
/stopcheques:
  /requests:
     post:
       description: Create a Stop Cheque Request
       body:
         application/json:
           schema: request
       responses:
         200:
           body:
             application/json:
               schema: request
               example: !include sc-request.sample
         400:
           body:
             application/json:
               schema: exception
               example: !include exception.sample
     /{stopChequeRequestId}:
       get:
         description: Get a specific Stop Cheque Request
         responses:
           200:
             body:
               application/json:
                 schema: request
                 example: !include sc-request.sample
           404:
             body:
               application/json:
                 schema: exception
                 example: !include exception.sample	

______________________________________
pom.xml	
<build>
        <plugins>
            <plugin>
                <groupId>com.phoenixnap.oss</groupId>
                <artifactId>springmvc-raml-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <ramlPath>src/main/raml</ramlPath>
                    <basePackage>com.gen.wow</basePackage>
                    <outputRelativePath>src/generated</outputRelativePath>
                    <baseUri>/application</baseUri>
                    <rule>com.phoenixnap.oss.ramlapisync.generation.rules.Spring4ControllerStubRule</rule>
                    <ramlPath>src/main/raml</ramlPath>
                    <schemaLocation>src/main/raml</schemaLocation>
                    <outputRelativePath>src/generated</outputRelativePath>
                    <addTimestampFolder>false</addTimestampFolder>
                    <basePackage>com.gen.wow</basePackage>
                    <seperateMethodsByContentType>false</seperateMethodsByContentType>
                    <ruleConfiguration>
                    </ruleConfiguration>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-springmvc-endpoints</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate-springmvc-endpoints</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by kurtpa** [comment]
The attached raml is missing indentation and included schemas. Please make sure to format it correctly and that it causes the issue.

On another note, running the job in debug mode (adding -X to the mvn command) might give you a longer stacktrace which will help debugging
