### ISSUE TITLE
ability to return any type from controller 

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#62]
Hi,
Could it be possible to have a parameter to not specify a type in a response entity ?

present:
```java
@RequestMapping(value = "", method = RequestMethod.GET)
    public ResponseEntity<List<com.test.samples.model.SampleUnit>> getSampleUnits();
```

expected:
```java
@RequestMapping(value = "", method = RequestMethod.GET)
    public ResponseEntity<?> getSampleUnits();
```

It'll allow, in the controller, to return something like following in case of an exception:

```java
...
   }catch(Exception ex){
        return new ResponseEntity<>(ex.getMessage, HttpStatus.BAD_REQUEST);
    }
```

Thanks.

**Comment by kurtpa** [comment]
Currently we are achieving this by having our code throw exceptions, and then using @ExceptionHandler (https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc) to transform those exceptions into HTTP requests. The benefit of this approach is that it does not clutter controllers with a lot of similar try catch blocks to convert errors into say HTTP 400/500/etc. Also the approach is a bit more standardised and less prone to human error

To achieve what you want we can probably create a configuration which will omit response types in the plugin, however i'm not sure we can do it selectively

**Comment by mehdijouan** [comment]
This solution works if I use an external class and the `@ControllerAdvice` annotation.
When I try the `@ExceptionHandler` annotation in my controller, nothing happens. It's maybe because the handler method is not located into the `...ControllerDecorator class` which has the annotation `@RestController`.
I tried this code from the doc:

```java
  @ExceptionHandler(Exception.class)
  public ModelAndView handleError(HttpServletRequest req, Exception exception) {
    logger.error("Request: " + req.getRequestURL() + " raised " + exception);

    ModelAndView mav = new ModelAndView();
    mav.addObject("exception", exception);
    mav.addObject("url", req.getRequestURL());
    mav.setViewName("error");
    return mav;
  }
```

**Comment by kurtpa** [comment]
Yes it needs to either be in a class with @RestController or the @ControllerAdvice. We have classes specific to this since usually the way exceptions are translated  is not controller specific 

We also use custom exceptions for 40x responses to allow for error codes/reasons.

**Comment by mehdijouan** [comment]
ok, thanks for the explanation
