### ISSUE TITLE
Support of traits

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#63]
Hi,
I did not find how traits are handled by the springmvc-raml-plugin. 
Does it manages them ?

Thanks.

**Comment by kurtpa** [comment]
They are transparent to it,  the raml parser automatically expands resources with stuff they inherit from types and traits

**Comment by mehdijouan** [comment]
Right, it works well.. when the raml is correctly formatted 😄 .
