### ISSUE TITLE
[Code to RAML] plugin doesn't support DeferredResults

### ISSUE THREAD

**Issue by arielsegura** [phoenixnap/springmvc-raml-plugin#69]
This is the generated RAML given a controller which return value is a deferred result:

#%RAML 0.8
title: bla
version: "1"
baseUri: /v1
mediaType: application/json
/v1: 
    displayName: V1 Resource
    description: V1 Resource
    /organizations: 
        displayName: Organizations Resource
        description: Organizations Resource
        /{organizationId}: 
            displayName: "{organizationId} Resource"
            description: "{organizationId} Resource"
            /context: 
                displayName: Context Resource
                description: Context Resource
                get: 
                    description: getUserData
                    queryParameters: 
                        arg2: 
                            displayName: arg2
                            type: string
                            required: false
                            repeat: false
                    responses: 
                        "200": 
                            description: Successful Response
                            body: 
                                application/json: 
                                    schema: |
                                        {
                                          "type" : "object",
                                          "id" : "urn:jsonschema:org:springframework:web:context:request:async:DeferredResult<com:bla:myPojo>",
                                          "properties" : {
                                            "result" : {
                                              "type" : "any"
                                            },
                                            "setOrExpired" : {
                                              "type" : "boolean"
                                            }
                                          }
                                        }

I expected to have a different schema that describes my pojo.

**Comment by kurtpa** [comment]
We are not unwrapping DeferredResult currently, and as such it is being passed entirely to JsonSchema2Pojo. This could be an enhancement whereby the DeferredResult is ignored and its inner type is passed on for generation. 

When reporting issues relating to code-to-raml please provide an entire code snippet of the controller being generated to aid replication.

**Comment by fgather** [comment]
Same problem occurs with Spring ResponseEntity: 
"id" : "urn:jsonschema:org:springframework:http:ResponseEntity<java:util:Collection<bla:myType>>"

**Comment by kurtpa** [comment]
I'll give this a look tomorrow :)

**Comment by kurtpa** [comment]
done, will be released with 0.7.2
