### ISSUE TITLE
Need to add example in Request body and Response body in RAML

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#73]
Hi Kurtpa ,
I have example of all request and response of RAML generated RAML. 
is there any provision to add this in utility?

**Comment by kurtpa** [comment]
Yes at the moment there is no way to infer this from Spring so you need to use the @Example annotation which  is in the springmvc-raml-annotations module

**Comment by kurtpa** [comment]
Did you manage to use this feature? can i close this issue?

**Comment by rahulkamuni** [comment]
Hi Kurt Paris,
I have modified my local code as per my requirement. Sure you can close my
issue.

Thanks
Rahul Kamuni

**Comment by kurtpa** [comment]
Did the @example help or did you use an alternate approach?

**Comment by rahulkamuni** [comment]
Actually my requirement was different I don't have access to modify the
beans and can't add any annotation in code.
So I have mapped one excel for request and response example with some
uniqueness of each operation.
From that excel I am picking example of request and response adding it to
RAML.

**Comment by kurtpa** [comment]
this idea of having examples in a seperate file could make sense. thanks for the idea
