### ISSUE TITLE
Use commons-lang3 instead commons-lang

### ISSUE THREAD

**Issue by reedemerrs** [phoenixnap/springmvc-raml-plugin#78]
Try to use 
`<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
</dependency>`
instead
`<dependency>
    <groupId>commons-lang</groupId>
    <artifactId>commons-lang</artifactId>
    <optional>true</optional>
</dependency>`

commons-lang is needed for ToStringBuilder, HashCodeBuilder and EqualsBuilder.
This dependency could also be included in plugin itself.

**Comment by reedemerrs** [comment]
This is already supported by configuring plugin in pom.xml with
```
<generationConfig>
         ...
	<useCommonsLang3>true</useCommonsLang3>
</generationConfig>
```

**Comment by kurtpa** [comment]
:)
