### ISSUE TITLE
Can we add two response schemas in RAML

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#86]
Hi Kurtpa,
In my project all POJO class are extending one parent class "ResponseEdo". 
In my controller there is one method  whose  return type is "ResponseEdo" but the actual it returning child class ,here I am typecasting the child class to parent class "ResponseEdo" . 
As the return type is "ResponseEdo" so I am getting schema of "ResponseEdo" in RAML but actually it is  returning child class. 
Is there any to add two schemas in API response of RAML?

**Comment by kurtpa** [comment]
As far as i'm aware RAML does not support multiple response schemas for the same content type. Jsonschema does support polymorphism but at the moment there is no way for the generator to group all child classes together

In the Java -> RAML path,  the generator is using the method signature of the controller to decide which class to assign to the api call. You would need to put the child class as the return type of the controller method. If you need a signature with the parent for some other reason, you could possibly hide your controller method behind an interface and in the interface declare the parent class as the return type.

**Comment by rahulkamuni** [comment]
okay's thanks for sharing knowledge about RAML.
