### ISSUE TITLE
RAML root level resource URI issue

### ISSUE THREAD

**Issue by rahulkamuni** [phoenixnap/springmvc-raml-plugin#88]
Hi Kurtpa,
In my controller the class level URI is "/" and for method level URI I have proper REST URI. 
After RAML generation of above controller. In generated RAML the root level resource URI is mapping with method level URI . As per my view the root level URI of RAML should be "/" . 
The RAML which I have generated is right one or I had missed something ?

**Comment by kurtpa** [comment]
Hiya,

could you post some example URLs please because i'm not sure i'm understanding you
