### ISSUE TITLE
JSR 310 types not correctly recognized

### ISSUE THREAD

**Issue by bendem** [phoenixnap/springmvc-raml-plugin#89]
I'm using `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` to convert dates in my DTOs and this plugin generates reflection based schemas for JSR 310 types instead of formatted strings.

i.e. `LocalDate`:

``` json
"birthDate" : {
  "type" : "object",
  "id" : "urn:jsonschema:java:time:LocalDate",
  "properties" : {
    "year" : {
      "type" : "integer"
    },
    "month" : {
      "type" : "string",
      "enum" : [ "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" ]
    },
    "era" : {
      "type" : "object",
      "id" : "urn:jsonschema:java:time:chrono:Era",
      "properties" : {
        "value" : {
          "type" : "integer"
        }
      }
    },
    "dayOfYear" : {
      "type" : "integer"
    },
    "dayOfWeek" : {
      "type" : "string",
      "enum" : [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
    },
    "leapYear" : {
      "type" : "boolean"
    },
    "dayOfMonth" : {
      "type" : "integer"
    },
    "monthValue" : {
      "type" : "integer"
    },
    "chronology" : {
      "type" : "object",
      "id" : "urn:jsonschema:java:time:chrono:IsoChronology",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "calendarType" : {
          "type" : "string"
        }
      }
    }
  }
}
```

I expected instead

``` json
"birthDate": {
  "type": "string",
  "format": "date"
}
```

**Comment by kurtpa** [comment]
Kindly refer to the documentation of the jsonschema2pojo project.  I think there is a configuration you can use to toggle this behavior

**Comment by bendem** [comment]
Sorry if I misunderstood, but isn't jsonschema2pojo a tool to generate POJOs from json schemas? I'm trying to go the other way: generating raml and schemas from existing code.

Using
```xml
<plugin>
    <groupId>com.phoenixnap.oss</groupId>
    <artifactId>springmvc-raml-plugin</artifactId>
    <version>0.8.4</version>
    <configuration>
        <outputRamlFilePath>/src/main/resources/api.raml</outputRamlFilePath>
        <restBasePath>/</restBasePath>
        <version>0.0.1</version>
    </configuration>
    <executions>
        <execution>
            <id>generate-springmvc-api-docs</id>
            <phase>compile</phase>
            <goals>
                <goal>generate-springmvc-api-docs</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by kurtpa** [comment]
Sorry,  i misunderstood your usecase. 

We are using jackson to generate the schema from the pojo.  IIRC The code is in the SchemaHelper class. 

I can look into what customisation options there are in this area,  however code->raml is lower priority than codegeneration at present for us

**Comment by bendem** [comment]
I've been looking into this but I can't figure out how set it up. Where would I tell jackson about custom schema for some classes?

**Comment by bendem** [comment]
Registering the JavaTimeModule fixes this (https://github.com/bendem/springmvc-raml-plugin/commit/1223faf07751ffcf4085bf692c46d79eb2af5725#diff-d031fbe4ee5dd48d5640daacf807d971R235). Not sure if there is a way to make the `SerializationFeature` configurable tho.

**Comment by kurtpa** [comment]
cool! to be honest i dont think there is any value in supporting the old format - i would love a PR for that commit :)

**Comment by tspaeth** [comment]
👍
